Client:
    type: entity
    table: client
    id:
        idClient:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_client
            generator:
                strategy: SEQUENCE
    fields:
        nom:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
        prenom:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
        civilite:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
        adresse:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        cp:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
        ville:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        pays:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        telephone:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
        username:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
        password:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
    lifecycleCallbacks: {  }
